### ISSUE TITLE
[bug] Loading an obj shows a black screen

### ISSUE THREAD

**Issue by littlelum** [hlorenzi/kmp-editor#2]
When I load an obj, the view just shows a black screen. I tried clicking "center view," but nothing changes. I'm using 0.5.0
Also, the buttons for loading a kcl/brres don't work, you have to use the load model button. the KCL doesn't show colors even though show colors is checked, and loading a brres doesn't do anything at all.

**Comment by hlorenzi** [comment]
Is there any way you could get me the files you're having trouble with?
Are you on Discord? Mine is: hlorenzi#7149

The buttons for loading kcl/brres, if I remember correctly, load a fixed-name file from the same folder as the current .kmp file -- if you don't have the correct files in the folder, you should indeed use the generic "load model" button to load from somewhere else.

**Comment by littlelum** [comment]
Yeah, I don't really use it, but I'm on it. I sent you a friend request so I can communicate with you there.
All the files were used with "load model"

**Comment by douglasb78** [comment]
Cara, obrigado por fazer o KMP-Editor. 👍
Foi o único editor que funcionou no meu PC.
