### ISSUE TITLE
Where is KCL import?

### ISSUE THREAD

**Issue by ThePlayerRolo** [hlorenzi/kmp-editor#26]
MY version of this kmp-editor has no KCL import. Help? Screenshot: 
![image](https://github.com/user-attachments/assets/7c3f9b70-004f-4310-9a6a-5782b741a5a0)

**Comment by ThePlayerRolo** [comment]
btw, I'm replacing  N64 sherbert land

**Comment by shxd10** [comment]
click the load model button ._.

**Comment by ThePlayerRolo** [comment]
> click the load model button ._.

sorry, sorry, I'm just new here. I've been having troubles with scaling not working and weird collision and model errors when I load the track. But I don'
t think it has to do with the plugin.
