### ISSUE TITLE
Ghost Kanji TypeError

### ISSUE THREAD

**Issue by ghost** [hlorenzi/kmp-editor#9]
Attempting to search for (Phantom Kanji), a tag available for yuurei moji such as 妛 has a javascript pop up box with an error

An error occurred!

TypeError: NetworkError when attempting to fetch resource.

**Comment by hlorenzi** [comment]
Is this about the [Jisho](https://jisho.hlorenzi.com/)? This repository is completely unrelated!

In any case, what query are you trying? I can see now that searching for `(phantom kanji)` doesn't work properly... Probably has something to do with the parentheses? You can try searching for `phantom kanji #k` instead, which should give the results you want.

You can add me or join my server on Discord if you want to discuss it further!

**Comment by ghost** [comment]
Was using your site. Learned about it earlier and thought that the proper tag to find them would be `(phantom kanji)` and oops, Thank you for the proper tag, Just wanted to alert to the javascript weirdness if it was a problem. Thank you.
